"""Domain knowledge used by the local validation agents.

The lists here intentionally mirror the product design rather than a production
knowledge base. In production they should be loaded from managed configuration
or the business Excel sheets.
"""

STANDARD_DOCUMENT_TYPES = {
    "identity_card_front": {
        "name": "身份证正面",
        "category": "standard_certificate",
        "role": "人身份强证据",
        "keywords": ["身份证", "人像面", "identity"],
    },
    "identity_card_back": {
        "name": "身份证反面",
        "category": "standard_certificate",
        "role": "人身份强证据",
        "keywords": ["身份证反面", "国徽面"],
    },
    "business_license": {
        "name": "营业执照",
        "category": "standard_certificate",
        "role": "企业身份强证据",
        "keywords": ["营业执照", "统一社会信用代码", "business license"],
    },
    "driving_license": {
        "name": "驾驶证",
        "category": "standard_certificate",
        "role": "人身份辅助证据",
        "keywords": ["驾驶证", "准驾"],
    },
    "electronic_driving_license": {
        "name": "电子驾驶证",
        "category": "standard_certificate",
        "role": "人身份辅助证据",
        "keywords": ["电子驾驶证"],
    },
    "vehicle_license": {
        "name": "行驶证",
        "category": "standard_certificate",
        "role": "车辆强证据",
        "keywords": ["行驶证", "车辆识别代号", "号牌号码", "vehicle license"],
    },
    "electronic_vehicle_license": {
        "name": "电子行驶证",
        "category": "standard_certificate",
        "role": "车辆强证据",
        "keywords": ["电子行驶证", "2024版电子行驶证"],
    },
    "entry_bill": {
        "name": "关单",
        "category": "standard_certificate",
        "role": "进口车车辆强证据",
        "keywords": ["关单", "进口", "海关"],
    },
    "receipt": {
        "name": "新车购车发票",
        "category": "standard_certificate",
        "role": "新车车辆与车主证据",
        "keywords": ["购车发票", "发票号码", "开票日期"],
    },
    "electronic_receipt": {
        "name": "电子发票",
        "category": "standard_certificate",
        "role": "新车车辆与车主证据",
        "keywords": ["电子发票"],
    },
    "vehicle_certification": {
        "name": "新车合格证",
        "category": "standard_certificate",
        "role": "新车车辆强证据",
        "keywords": ["合格证", "车辆合格证"],
    },
    "vehicle_register_cert": {
        "name": "机动车登记证书",
        "category": "standard_certificate",
        "role": "车辆登记和过户辅助证据",
        "keywords": ["机动车登记证书", "登记证书"],
    },
    "residence_permit": {
        "name": "港澳台/外国人证件",
        "category": "standard_certificate",
        "role": "人身份证据",
        "keywords": ["港澳台", "居住证", "外国人永久居留"],
    },
}

NON_STANDARD_DOCUMENT_TYPES = {
    "quotation": {
        "name": "历史报价单",
        "category": "non_standard",
        "role": "历史方案/交易凭证",
        "keywords": ["报价单", "报价", "交易号", "分享号"],
    },
    "other_quotation": {
        "name": "他司报价单",
        "category": "non_standard",
        "role": "方案参考证据",
        "keywords": ["他司报价", "其他保险公司", "人保", "太保", "报价截图"],
    },
    "insurance_policy": {
        "name": "保单",
        "category": "non_standard",
        "role": "历史承保凭证",
        "keywords": ["保单", "电子保单", "保险单"],
    },
    "consistency_report": {
        "name": "一致性报告",
        "category": "non_standard",
        "role": "车型辅助证据",
        "keywords": ["一致性报告", "一致性证书"],
    },
    "vehicle_nameplate": {
        "name": "车辆铭牌",
        "category": "non_standard",
        "role": "车型/车架辅助证据",
        "keywords": ["铭牌", "车辆铭牌"],
    },
    "inspection_sheet": {
        "name": "检验单",
        "category": "non_standard",
        "role": "车辆辅助证据",
        "keywords": ["检验单", "随车检验"],
    },
    "contract": {
        "name": "合同",
        "category": "non_standard",
        "role": "交易辅助证据",
        "keywords": ["销售合同", "预定合同", "订购合同", "合同"],
    },
    "letter_of_authorization": {
        "name": "授权委托书",
        "category": "non_standard",
        "role": "授权关系证据",
        "keywords": ["授权委托书", "授权书"],
    },
    "vehicle_delivery_authorization": {
        "name": "投车关系授权书",
        "category": "non_standard",
        "role": "投保关系证据",
        "keywords": ["投车关系", "投车关系授权书"],
    },
    "handwritten_note": {
        "name": "手写单证",
        "category": "non_standard",
        "role": "低置信辅助证据",
        "keywords": ["手写", "手机号", "车身价"],
    },
}

DOCUMENT_TYPES = {**STANDARD_DOCUMENT_TYPES, **NON_STANDARD_DOCUMENT_TYPES}

DOCUMENT_FIELD_MATRIX = {
    "identity_card_front": [
        "ownerName",
        "ownerIdType",
        "ownerIdNo",
        "ownerGender",
        "ownerBirthday",
        "ownerAddress",
    ],
    "identity_card_back": [
        "ownerAuthority",
        "ownerCertificateIssueDate",
        "ownerCertificateValidDate",
        "ownerLongTerm",
    ],
    "business_license": [
        "ownerName",
        "ownerIdType",
        "ownerIdNo",
        "ownerPersonnelType",
        "ownershipAttributeCode",
        "legalRepresentative",
        "ownerAddress",
    ],
    "driving_license": [
        "ownerName",
        "ownerIdType",
        "ownerIdNo",
        "ownerGender",
        "ownerBirthday",
        "ownerAddress",
    ],
    "electronic_driving_license": [
        "ownerName",
        "ownerIdType",
        "ownerIdNo",
        "ownerGender",
        "ownerBirthday",
        "ownerAddress",
    ],
    "vehicle_license": [
        "vehicleLicenseNo",
        "frameNo",
        "engineNo",
        "ownerName",
        "vehicleType",
        "usageAttributeCode",
        "registerDate",
        "vehicleIssueDate",
        "seats",
        "wholeWeight",
        "brandName",
        "modelName",
    ],
    "electronic_vehicle_license": [
        "vehicleLicenseNo",
        "frameNo",
        "engineNo",
        "ownerName",
        "vehicleType",
        "usageAttributeCode",
        "registerDate",
        "vehicleIssueDate",
        "seats",
        "brandName",
        "modelName",
    ],
    "receipt": [
        "ownerName",
        "ownerIdNo",
        "vehicleLicenseNo",
        "frameNo",
        "engineNo",
        "brandName",
        "modelName",
        "price",
        "billDate",
        "invoiceNo",
    ],
    "electronic_receipt": [
        "ownerName",
        "ownerIdNo",
        "vehicleLicenseNo",
        "frameNo",
        "engineNo",
        "brandName",
        "modelName",
        "price",
        "billDate",
        "invoiceNo",
    ],
    "vehicle_certification": [
        "frameNo",
        "engineNo",
        "brandName",
        "modelName",
        "vehicleType",
        "seats",
        "wholeWeight",
        "engineDesc",
        "power",
        "speed",
    ],
    "entry_bill": ["frameNo", "engineNo", "brandName", "modelName", "vehicleType"],
    "quotation": [
        "historyTransNo",
        "transNo",
        "vehicleLicenseNo",
        "frameNo",
        "ownerName",
        "insuranceName",
        "coverage",
        "unAutoProductInfo",
        "premium",
    ],
    "other_quotation": [
        "vehicleLicenseNo",
        "frameNo",
        "ownerName",
        "insuranceName",
        "coverage",
        "premium",
    ],
    "insurance_policy": [
        "policyNo",
        "vehicleLicenseNo",
        "frameNo",
        "ownerName",
        "applicantName",
        "insuredName",
        "insuranceName",
        "premium",
    ],
    "consistency_report": [
        "frameNo",
        "engineNo",
        "brandName",
        "modelName",
        "vehicleType",
        "seats",
        "wholeWeight",
        "engineDesc",
        "power",
    ],
    "vehicle_nameplate": ["frameNo", "engineNo", "brandName", "modelName", "wholeWeight"],
    "inspection_sheet": ["frameNo", "engineNo", "brandName", "modelName", "vehicleType"],
    "vehicle_register_cert": [
        "vehicleLicenseNo",
        "frameNo",
        "engineNo",
        "ownerName",
        "registerDate",
        "specialCarDate",
        "vehicleType",
        "usageAttributeCode",
    ],
    "letter_of_authorization": [
        "ownerName",
        "ownerIdNo",
        "applicantName",
        "applicantIdNo",
        "vehicleLicenseNo",
        "frameNo",
    ],
    "vehicle_delivery_authorization": [
        "ownerName",
        "ownerIdNo",
        "applicantName",
        "applicantIdNo",
        "vehicleLicenseNo",
        "frameNo",
    ],
}

STAGE_HIGH_RISK = {"insuring", "underwriting", "payment", "policy_delivering", "invoicing", "policy_issued"}

RELATIONSHIP_TYPES = [
    "identifies",
    "registered_to",
    "role_of",
    "responds_to",
    "modifies",
    "confirms",
    "contradicts",
    "supersedes",
    "derived_from",
    "wakes",
    "starts",
    "abandons",
]
